### ISSUE TITLE
Suggestion: Remove Numbers

### ISSUE THREAD

**Issue by GershonR** [byYottaFLOPS/EasyScoreboards#1]
If possible to remove the line numbers on the scoreboard.

**Comment by jonas-peeters** [comment]
I searched for it, but I think there no option to do that with the Sponge API.

And as the numbers are the actual scores and the client has to draw it in the correct order using them I don't think it will be possible in the future.

If you know an option please tell me where to find it or how to implement it.

**Comment by GershonR** [comment]
I looked into other scoreboard plugins and it uses the numbers as values, is it possible to change things like `PLAYERCOUNT`, `PLAYERBALANCE` to use the numbers?

**Comment by jonas-peeters** [comment]
This would be possible but not really functional. 

Let's say, we use `PLAYERCOUNT`.
If there is only one player on the server, then the row showing the number of player would be at the bottom. When the number of players is rising, this row would move upwards.

Therefor you couldn't really design such a scoreboard.

**Comment by ghost** [comment]
are you able to at least change the color of the numbers to something more hidden? like dark grey?

**Comment by jonas-peeters** [comment]
I added the feature in the latest release
