### ISSUE TITLE
Colors aren't working in the latest build

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#10]
Title. They show as &<color> in the scoreboard.

**Comment by jonas-peeters** [comment]
Are you using them with with the percentage sign?  e.g. `%&a%`

**Comment by Eufranio** [comment]
No, colors should be used that way?

**Comment by Eufranio** [comment]
Hm, yep they should, thanks. The wiki needs to be updated.

**Comment by Eufranio** [comment]
But, with scoreboards being that way, they are a lot more larger: 

![ola](http://image.prntscr.com/image/7f98b5a3e73d400d8600bb03dd81f31c.png)

And i just want to write "&d&lX Magi&a&lBeta &d&lX"

**Comment by Eufranio** [comment]
yeah opened a new issue
