### ISSUE TITLE
Scoreboard is muuuuuch more complicated

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#11]
Why can't you make the commands simpler?

`/esb set 0 "&d&lMagi&a&lBeta"` instead `/esb set 0 "%d%%&l%Magi%a%%&l%Beta"`

**Comment by jonas-peeters** [comment]
I'll guess it is. 
I just thought if I add % as a separator for the placeholders, it would make sense to do this on the colors like `GREEN` and the styles like `ITALIC` to. 
That way you could, for whatever reason, write team colors in caps into the scoreboard or whatever.
For consistency I added them the to the abbreviations, too.

Maybe I leave them on the written color and style strings but remove them from their abbreviations.

**Comment by Eufranio** [comment]
You can keep the % there, but only for variables like PLAYERBALANCE, not colors (as they are used with the &)

**Comment by jonas-peeters** [comment]
Changed it in 1.7.2
