### ISSUE TITLE
Can't use more than one color per line

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#13]
Doesn't matter how I try, i can never get more than 1 color per line working. Tried:

```
&d&lMagi;&a&lBeta
```
and
```
&d&lMagi&a&lBeta
```
and none of them work.

**Comment by jonas-peeters** [comment]
On my test server your first variant worked perfectly fine. 
Are you seeing the color codes in the scoreboard?

**Comment by Eufranio** [comment]
No, but the scoreboard will only show the first color, not the second... The text appears to be ALL purple

**Comment by jonas-peeters** [comment]
I get this as a result: 
<img width="220" alt="screen shot 2016-12-31 at 01 14 03" src="https://cloud.githubusercontent.com/assets/9808918/21574622/747b2ae2-cef6-11e6-96a5-fec5813b6699.png">

Could you send the complete line from the config or the config file itself?

**Comment by Eufranio** [comment]
```
    line {
        "0"="&d&l   ✖ Magi;&a&lBeta &d&l✖   "
```

**Comment by Eufranio** [comment]
Got it working, I forgot a **;** after **Beta**. You could remove this...

**Comment by Eufranio** [comment]
![a](http://image.prntscr.com/image/edbb18b665884a0aa3025249051892b5.png)

RIP

```
    line {
        "0"="&d&l   ✖ ;&e&lMagi;&a&lBeta; &d&l✖   "
```
is it wrong?
