### ISSUE TITLE
Wrong money value

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#18]
I'm using the %PLAYERBALANCE% placeholder, and it's showing the value wrongly. I have TotalEconomy as economy plugin, it's reporting that my balance is 979:

![1](http://image.prntscr.com/image/c8747d3f223846408d2e7439ee86fbaf.png)

But, in the scoreboard, it's reporting a wrong value:

![2](http://image.prntscr.com/image/07c94ef856564603a4ac9f8a06169eb0.png)

I don't know where it's getting this value. My config:

```
scoreboard {
  countdown {
    chat=true
    command="say The countdown is over"
    time=11
    title=true
    xp=false
  }
  hideFor=" "
  lines=[
    "number=%TPS%, text=&f&l ➤ TPS",
    "number=-1, text=&b&l✖ MagiBeta ✖",
    "number=%ONLINECOUNT%, text=&f&l ➤ Jogadores",
    "number=%PLAYERBALANCE%, text=&f&l ➤ Money"
  ]
  showForAll=true
}
```

**Comment by ghost** [comment]
Up, I have the same problem... it shows the money of an other player, and not myself...
