### ISSUE TITLE
2.1.0 - Number of line bug and error task

### ISSUE THREAD

**Issue by comdarksider** [byYottaFLOPS/EasyScoreboards#21]
I use EasyScoreboards 2.1.0.  I use PlaceholderAPI 3.8 for expansion of available value.
number of line bug because sort of number high to low from first line.  It must sort of number low to high from first line.   Please fix this bug.

Link picture Details :  https://www.mx7.com/view2/zK6geOdfEgBRi4hz
My file config :   https://drive.google.com/open?id=0B0YuIZTzdfDHdE9VOUFGTXFLU2s

Error task to run :
1.  In pastebin -  http://pastebin.com/tuzJyYAu
2.  In github -  https://gist.github.com/comdarksider/f5c29c52cb3b28fddfaac921148288dc

**Comment by jonas-peeters** [comment]
I currently can't see your image (the server seems to be down), however I see what you mean.

Minecraft itself will always put the line with the highest score to the top. This is nothing I can interfere with. Therefor you have to give the line on the top the highest number and the line at the bottom the lowest. (The title will still be -1 tho.)

Thanks for reporting the bug that caused the scoreboard to break. This should work in the latest version (2.1.1).
