### ISSUE TITLE
Showing Wrong Playername

### ISSUE THREAD

**Issue by ghost** [byYottaFLOPS/EasyScoreboards#22]
Using EasyScoreboards-2.1.1 on SpongeForge 1.10.2-2281-5.2.0-BETA-2350 with PlaceholderAPI 3.11

So, anyone logging into the server receives all of the information for whichever character was logged in first. Example: Character1 logs in followed by Character2 and Character3. Character1 displays there own player information, but -2 and -3 both display Character1's player information.

Just thought you'd like to know... I don't think that this was happening with PlaceholderAPI 3.9. I just updated that today...

**Comment by ghost** [comment]
It definitely appears to be an issue between your plugin and PlaceholderAPI. I just changed PlaceholderAPI to version 3.10, and I am no longer experiencing this issue.

**Comment by johnfriedrich** [comment]
Same issue with EasyScoreboards 2.3 + PlaceholderApi 4.4 + Pixelmon Placeholder 1.2.1 on Sponge api 7

**Comment by uzmanshafi** [comment]
still this issue is there till this day how can i fix it please help me

**Comment by jonas-peeters** [comment]
Finally fixed in the latest version. Thanks for your help.
