### ISSUE TITLE
BungeeCord problem on death

### ISSUE THREAD

**Issue by Krosta8** [byYottaFLOPS/EasyScoreboards#27]
Hello,
I discovered a problem with EasyScoreboard which is installed on Sponge server, when it is connected on BungeeCord.
I got this error: https://pastebin.com/Hsf1TtSS 
It is happend always, when player die. 

I tried to do /esb hide and then die, everything okay, but with shown scoreboard, i got kick.

I'm using EasyScoreboard v2.2

**Comment by Eufranio** [comment]
You could remove the scoreboard on death as a workaround, @byYottaFLOPS...

**Comment by johnfriedrich** [comment]
Still an issue
https://pastebin.com/knYct4SM

**Comment by jonas-peeters** [comment]
I have finally been able to reproduce this error and it is now fixed in the latest version.
