### ISSUE TITLE
Scoreboard only translates the first colorcode in each line

### ISSUE THREAD

**Issue by johnfriedrich** [byYottaFLOPS/EasyScoreboards#30]
http://prntscr.com/hvihit
results in 
http://prntscr.com/hvihtk

**Comment by jonas-peeters** [comment]
Try placing semicolons `;` after in front of the the next color code. I forgot to write that into the wiki.

This should work:
`text=&a%trainer_dexcount%; &fvon; &2%pixelmon_dexsize%`
