### ISSUE TITLE
The information of the first person who is connected is displayed

### ISSUE THREAD

**Issue by ziceptor** [byYottaFLOPS/EasyScoreboards#34]
https://i.imgur.com/og7rBGV.png

forge-1.12.2-14.23.2.2611-universal.jar
spongeforge-1.12.2-2611-7.1.0-BETA-2931.jar
~~EasyScoreboards.jar 2.3 latest~~

Edit:
EasyScoreboards.jar **2.5**

Output of the command /sp plugins: EasyScoreboards.jar 2.3 

mcmod.info
[
    {
        "modid": "de_yottaflops_easyscoreboard",
        "name": "EasyScoreboards",
        "version": "**2.3**",
        "description": "A plugin to easily create scoreboards for lobbys, etc.",
        "authorList": [
            "YottaFLOPS"
        ],
        "dependencies": [
            "spongeapi@7.0.0"
        ],
        "requiredMods": [
            "spongeapi@7.0.0"
        ]
    }
]

**Comment by jonas-peeters** [comment]
Could you append your config file so that I can test with it to find the bug?

**Comment by ziceptor** [comment]
```
scoreboard {
    countdown {
        chat=false
        command=""
        time=0
        title=false
        xp=false
    }
    hideFor=" "
    lines=[
        "number=-1, text=&l&2zi;&l&6CRAFT",
        "number=9, text= ",
        "number=8, text=&fIP: ;&6127.0.0.1",
        "number=7, text=&fИгроков: ;&f ;&6%server_online% из %server_max_players%",
        "number=6, text= ",
        "number=5, text=&fГруппа: ;&6%player_prefix%",
        "number=4, text=&fИмя: ;&6%player%",
        "number=3, text=&fНа сервере: ;&6%nucleus_activetime%",
        "number=2, text=&fОграничения:",
        "number=1, text=&f|;&7 домов: ;&6%player_option_home-count%",
        "number=0, text=&fБаланс: ;&6%PLAYERBALANCE%"
    ]
    placeholderUpdateTicks=40
    showForAll=true
    tabFooter="+++"
    tabHeader="+++"
    tabRemovePlayerNames=false
}

```

**Comment by ziceptor** [comment]
At the moment I rolled back the version.

**Comment by Tollainmear** [comment]
Hi~ @ziceptor  could you plz tell me which version could solve this problem？I was troubled with this problem too 😅

**Comment by ziceptor** [comment]
EasyScoreboards 2.4.1

**Comment by Tollainmear** [comment]
thx a lot 😘

**Comment by SomeJakeGuy** [comment]
@byYottaFLOPS This is same issue still occuring in the latest version you just realeased. I use EasyScoreboards v2.5.1 and PlaceHolder API v4.4

**Comment by ThornsOfire** [comment]
Same issue here EasyScoreboards v2.5.1 and PlaceHolder API v4.4

**Comment by ThornsOfire** [comment]
Additional Info:
SpongeVanilla beta 59

Rolling back to EasyScoreboards 2.4.1 fixes the issue!

**Comment by Mike5357** [comment]
Also having this issue

**Comment by Luysita** [comment]
This is still happening!
