### ISSUE TITLE
Make line optional?

### ISSUE THREAD

**Issue by ryantheleach** [byYottaFLOPS/EasyScoreboards#4]
Hey a user named Siigari in #SpongeDev IRC was using your plugin and was wondering if you would kindly add support that the lines on /setline were optional.

What they mean by that, is having a "simple" scoreboard that doesn't have formatting or specific line orders and just orders things based on their natural ordering.

e.g. 

![image](https://cloud.githubusercontent.com/assets/141554/19481642/21e2fbe6-9596-11e6-81a8-60bca76e668c.png)

This is technically a duplicate of #1 But I'm just recreating to reiterate that this is a feature that people actually want, and that they don't necessarily want the scoreboard "designed"

**Comment by Eufranio** [comment]
I would like to have this feature as well...

**Comment by Eufranio** [comment]
Not really Sponge related, but ScoreboardStats does it and I neither my players worry about values moving in the scoreboard...
https://dev.bukkit.org/bukkit-plugins/scoreboardstats/

**Comment by jonas-peeters** [comment]
Possible in the latest release...
