### ISSUE TITLE
Wrong player info

### ISSUE THREAD

**Issue by RoydePanda** [byYottaFLOPS/EasyScoreboards#41]
Every player see the info of the first player who joined the server.

**Comment by Luysita** [comment]
Having this problem as well, using placeholders.

**Comment by arnekick** [comment]
Same here

**Comment by xXjojojXx** [comment]
Same here

**Comment by xXjojojXx** [comment]
This is still happening!
PlaceholderAPI-4.4
Easy Scoreboards [v2.5.1]

**Comment by Mdom10** [comment]
same here

**Comment by jonas-peeters** [comment]
Finally fixed in [v2.5.4](https://github.com/jonas-peeters/EasyScoreboards/releases/tag/v2.5.4) and later
