### ISSUE TITLE
multiple colorcodes

### ISSUE THREAD

**Issue by XiNaru** [byYottaFLOPS/EasyScoreboards#46]
Hey, i have see...
multiple colorcodes in one line doesnt work and the &r code doesnt work too.

&r Problem:
https://i.imgur.com/eYJnv2k.png
https://i.imgur.com/6OcaKad.png

multple color codes:
https://i.imgur.com/sZHYgJw.png
https://i.imgur.com/lBmd6v5.png

and sry but the useable line length is to small....

**Comment by jonas-peeters** [comment]
What exactly are you expecting `&r` to do? No [color](https://github.com/jonas-peeters/EasyScoreboards/wiki/Colors) or [style](https://github.com/byYottaFLOPS/EasyScoreboards/wiki/Styles) has `&r` as a code.

To use different colors/styles on the same line, create multiple sections using `;` as a separator. Use only one color and one style per section:

`&dWillkommen ;&c$player_displayname%`

**Comment by XiNaru** [comment]
quote:  What exactly are you expecting &r to do? No [color](https://github.com/jonas-peeters/EasyScoreboards/wiki/Colors) or [style](https://github.com/byYottaFLOPS/EasyScoreboards/wiki/Styles) has &r as a code.

&r is the color reset in minecraft. if i use the &r it uses the standard color after stat (in most situations is it white). 
https://www.spigotmc.org/attachments/example2-png.402641/
for expample type: &ahallo &rtest in chat and it works. &r resets the colorcode to default.


okay thanks THIS works...but an other problem is still there....
the line length:


https://i.imgur.com/xSKg8Bh.png

most lines longer as the last (the RANK PREFIX ingame is &f&dSpieler&f], also not very long)
but ingame:
https://i.imgur.com/fPucO45.png

edit: and NOW there is standing ERROR: null

**Comment by jonas-peeters** [comment]
Sorry, I don't know why this is happening. When the PlaceholderAPI plugin is installed, the text should be replaced accordingly. Are you sure, that the rank prefix is short enough to fit the 38 character limit? Is there anything in server indicating another problem with the plugin?

**Comment by XiNaru** [comment]
i have write you the right prefix and Owner prefix is &f[&4Owner&f]

this doesnt work too.
ich use luck perms und placeholderapi is installed

https://i.imgur.com/4Nebzvs.png
https://i.imgur.com/LhEsk5u.png
https://i.imgur.com/PPDCbJU.png
https://i.imgur.com/OJp14RS.png


is using ftbutilities too but only because chunk claiming. but i have shut down ranks in ftb
https://i.imgur.com/gMoUv7s.png



edit: also... its the same with suffix

https://i.imgur.com/Wh4NKAl.png
https://i.imgur.com/n1A5jOF.png

and the rank prefix/suffix are not long

edit2: now ingame is this
https://i.imgur.com/prbpruw.png

i dont have change anything in the config.

**Comment by XiNaru** [comment]
Solution:

Since I use LuckPerms, like most people, it didn't work with Papi %rank_prefix%.
I have now installed LuckHolders2 and it finally works.
