### ISSUE TITLE
same scoreboard for all players....

### ISSUE THREAD

**Issue by XiNaru** [byYottaFLOPS/EasyScoreboards#47]
sry but a new problem.

I have made a scoreboard with placeholders and for me it works.

![image](https://user-images.githubusercontent.com/29681441/177826733-f5614f48-3fbb-421d-88f7-cb8a15b1c647.png)
![image](https://user-images.githubusercontent.com/29681441/177826763-a6f5c503-866f-458a-8d69-60e89dfd05e9.png)

BUT my friend joined and has MY scoreboard, my name in scoreboard, my ranks, my money....not his own.

![image](https://user-images.githubusercontent.com/29681441/177826947-7fc0403f-6238-42d9-8178-81e0d16dc375.png)
sry this is a discord screenshot

**Comment by jonas-peeters** [comment]
Ok, I have released a [new version](https://github.com/jonas-peeters/EasyScoreboards/releases/tag/v2.5.2). Could you check out if the issue is still present there?

**Comment by XiNaru** [comment]
no the bug isn fixed.
NOW a new player joined the game, he has his own scoreboard but NOW I see his scoreboard

![image](https://user-images.githubusercontent.com/29681441/177969865-e78e3b41-bc69-48d6-9b20-256249133d87.png)
![image](https://user-images.githubusercontent.com/29681441/177970145-bfb9ee9a-f845-46f7-bdf7-11c1ae0c8a54.png)



iam xinaru he is Zeus

or must i delete the old config?

**Comment by XiNaru** [comment]
okay the bug isn fixed
i have delete the old config and add the lines new.
but the scoreboard dont show the own scoreboard always.


i do:
1. try with old config I have HIS scoreboard
2. i delete the old config and add the lines new, the /esb reload. short it work
3. we both disconnected from server and joined again. HE has now my scoreboard

**Comment by jonas-peeters** [comment]
Ok, I believe it has to do with the order the players join. I will have another look at it

**Comment by jonas-peeters** [comment]
Alright, I have updated some logic concerning the buffering of scoreboards. In addition, this version will log if placeholder usage is detected. You should not need to delete the config file. If the issue persists, please check in the server logs if it says "Detected use of placeholders" or "Detected *no* use of placeholders"

[EasyScoreboard-2.5.3.jar.zip](https://github.com/jonas-peeters/EasyScoreboards/files/9071342/EasyScoreboard-2.5.3.jar.zip)

**Comment by XiNaru** [comment]
sry but the problem ist there with the new version too.

08.07 17:27:59 [Server] Server thread/ERROR [Sponge]: The Scheduler tried to run the task de_yottaflops_easyscoreboard-S-3 owned by Plugin{id=de_yottaflops_easyscoreboard, name=EasyScoreboards, version=2.5.3, description=A plugin to easily create scoreboards for lobbys, etc., authors=[YottaFLOPS], source=./mods/EasyScoreboard-2.5.3.jar}, but an error occured.

**Comment by XiNaru** [comment]
now the plugin is crashed


![image](https://user-images.githubusercontent.com/29681441/178038266-ccfffba5-8040-45e3-83de-effb6fc8ead7.png)

**Comment by jonas-peeters** [comment]
Ok, this was probably due to another change I made. I apologize. Try with this version, if you could.
[EasyScoreboard-2.5.3.jar.zip](https://github.com/jonas-peeters/EasyScoreboards/files/9073943/EasyScoreboard-2.5.3.jar.zip)

**Comment by XiNaru** [comment]
ähm...i use 2.5.3?
you have uplöoad this above? this version i use and the error comes

**Comment by jonas-peeters** [comment]
It should be a new build with the same version number

**Comment by XiNaru** [comment]
ah okay i try it

**Comment by XiNaru** [comment]
okay tried.
scoreboard there but my fried has MY scoreboard

**Comment by jonas-peeters** [comment]
Do the logs now say either "Detected use of placeholders" or "Detected no use of placeholders"?

**Comment by XiNaru** [comment]
08.07 19:52:04 [Server] Server thread/INFO [EasyScoreboard: Config]: Detected use of placeholders

**Comment by jonas-peeters** [comment]
I believe that I have finally fixed the problem and in my testing it worked. Let me know if the problem persists for you.

[EasyScoreboard-2.5.3-2.jar.zip](https://github.com/jonas-peeters/EasyScoreboards/files/9076311/EasyScoreboard-2.5.3-2.jar.zip)

**Comment by XiNaru** [comment]
This time it looks like it's finally going to work.

Just a friend and I on the server, everyone had their own sb. we are both separately leased and jointed it was still each his own sb.

the only thing i forgot to test is the /esb reload command.

**Comment by jonas-peeters** [comment]
Amazing. Thanks for your help debugging this issue and your patience. I have created a new release [here](https://github.com/jonas-peeters/EasyScoreboards/releases/tag/v2.5.4) but it should be identical (apart from the version number) to the .jar posted above. Thanks again
