### ISSUE TITLE
TPS goes over 20

### ISSUE THREAD

**Issue by Eufranio** [byYottaFLOPS/EasyScoreboards#8]
Sometimes, the scoreboard shows the TPS over 20, I think you could fix this.

**Comment by jonas-peeters** [comment]
Fixed the issue that it goes over 20.0 when reloading.

Or did this happen to you elsewhere?

**Comment by Eufranio** [comment]
It happens randomly, and not only after reloads.

**Comment by Eufranio** [comment]
This is fixed in the latest release.
